title: Reymer Lab – Deciphering mechanisms of life
author:
  name: Anna Reymer 
  email: anna.reymer@gu.se
description: >
  We are a computational biophysics group working on deciphering mechanisms
  of eukaryotic transcriptional control and its dysregulation in disease; 
  and designing ways to employ this knowledge for medical purposes. 
  
theme: minima

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/annareym" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=4TfCOOIAAAAJ" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/anna-reymer/" }
